syntax = "proto3";
option go_package = "news-grpc/proto/news/v1;v1";

package news.v1;

import "news/v1/news.proto";

import "google/protobuf/empty.proto";


service NewsService {
  rpc Create(CreateRequest) returns (CreateResponse);
  rpc Get(GetRequest) returns (GetResponse);
   // Server side stream
  rpc GetAll(google.protobuf.Empty) returns (stream GetAllResponse);
  // Clinet side stream
  rpc UpdateNews(stream CreateRequest) returns (google.protobuf.Empty);
  // Bidirectional stream
  rpc DeletedNews(stream NewsID) returns (stream google.protobuf.Empty);

}